vpx set dofile abort exit
vpx set screen display -noprogress
tclmode

# Generated by Genus(TM) Synthesis Solution 17.12-s023_1, revision 1.245k
# Generated on: Fri Jan 05 21:48:34 EET 2018 (Fri Jan 05 19:48:34 GMT 2018)

tcl_set_command_name_echo on

set_log_file logs/lec.signoff.log -replace

usage -auto -elapse

set_verification_information fv_map_[get_db flow_vars_design_name]syn_optlec_db

read_implementation_information fv/[get_db flow_vars_design_name] -golden [get_db flow_vars_design_name]syn_optlec

set_parallel_option -threads 4 -license "xl lp gxl lpgxl eco ecogxl" -norelease_license

set env(RC_VERSION)     "17.12-s023_1"
set env(CDN_SYNTH_ROOT) "/sitework/soc/cdn_eval/tool/genus/17.12-s023_1/tools.lnx86"
set CDN_SYNTH_ROOT      "/sitework/soc/cdn_eval/tool/genus/17.12-s023_1/tools.lnx86"
set env(CW_DIR) "/sitework/soc/cdn_eval/tool/genus/17.12-s023_1/tools.lnx86/lib/chipware"
set CW_DIR      "/sitework/soc/cdn_eval/tool/genus/17.12-s023_1/tools.lnx86/lib/chipware"

set_lowpower_option -native_1801

set_lowpower_option -native_1801
set_lowpower_option -revised_analysis_style  pre_route

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_notranslate_modules -library -both <memory instances>

add_search_path . /sitework/soc/cdn_eval/tool/genus/17.12-s023_1/tools.lnx86/lib/tech -library -both
read_library -liberty -both -lp  a.lib b.lib ...

read_design -verilog95   -golden -lastmod -noelab dbs/syn_opt/[get_db flow_vars_design_name].syn_opt.lec
elaborate_design -golden -root {[get_db flow_vars_design_name]}

read_design -verilog95   -revised -lastmod -noelab dbs/opt_signoff/[get_db flow_vars_design_name].v
elaborate_design -revised -root {[get_db flow_vars_design_name]}

read_power_intent  -1801 -both ./invs_temp_dir/genus2invs.upf


report_design_data
report_black_box

set_flatten_model -gated_clock

add_pin_constraints 0 {scan_enable} -both

set_analyze_option -auto

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -extra -unreachable -notmapped
add_compared_points -all
compare -gate_to_gate

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information

tclmode
puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}
vpxmode
exit -f
