# Flowkit v19.10-s011_1
################################################################################
# Modus attributes
#
#  Attributes used to drive tool behavior.  Most typically these are root level
#  attributes.  All root attributes can be listed by using 'report_obj -all' or
#  by category using 'report_obj -all -verbose'
#
#  Further attribute help can be obtained by using the command 'help <ATTRIBUTE>'
#
#  The init_modus flow_step is provided to specify tool level options for
#  modus commands.  These are applied after loaded via the ini_atpg script
#  generated by write_dft_atpg in the genus_to_modus flow_step.
#
################################################################################

##############################################################################
# STEP init_modus
##############################################################################
create_flow_step -name init_modus -owner flow {
  # General attributes
  #-------------------------------------------------------------------------------
  #set_db workdir                              dft
  set_db stop_on_severity                     error
  
  #set_option outputdir                        [file join [get_db workdir] testresults]
  set_option stdout                           summary
  set_option log                              all
  
  # Design options
  #-------------------------------------------------------------------------------

  #set dft_synth_flow 1
  set sim_no_delay 1

  set_option cell [get_db flow_vars_design_name]
  set_db current_design [get_db flow_vars_design_name]
  
  # Memory models found in atpg/memory_udp_models.v
  set macro_models [list]
  foreach verilog [get_db flow_vars_dft_library] {
      if {![string match /opt/soc/work/mem/*_atpg.v $verilog] && ![regexp dft_lib $verilog]} {
          lappend macro_models $verilog
      }
  }

  if {[info exists dft_synth_flow]} {
      set_option designsource [concat [get_db flow_vars_data_directory]/dbs/syn_opt/[get_db flow_vars_design_name].v.gz $macro_models]
  } else {
      set_option designsource [concat [get_db flow_vars_data_directory]/dbs/opt_signoff/[get_db flow_vars_design_name].v.gz $macro_models]
  }
  
  set_option techlib [get_db flow_vars_dft_data_directory]/dft_lib_specify.v
  if {[file exists [get_db flow_vars_data_directory]/atpg/memory_udp_models.v]} {
      set_option techlib [concat [get_option techlib] [get_db flow_vars_data_directory]/atpg/memory_udp_models.v]
  }
  set_option allowmissingmodules              no
  
  #set_option sdc                              ""
  #set_option clockconstraints                 ""
  
  # Test mode building options
  #-------------------------------------------------------------------------------
  # If pinassign for these is found they are built with defined modedef
  # Note order important, fullscan_intest_opcg could be added
  set allowed_testmodes {}
  dict append allowed_testmodes COMPRESSION_DECOMP_INTEST      COMPRESSION_INTEST
  dict append allowed_testmodes FULLSCAN_INTEST                FULLSCAN_INTEST
  dict append allowed_testmodes COMPRESSION_DECOMP_INTEST_OPCG COMPRESSION_INTEST
  dict append allowed_testmodes COMPRESSION_DECOMP_EXTEST      COMPRESSION_EXTEST
  dict append allowed_testmodes FULLSCAN_EXTEST                FULLSCAN_EXTEST

  # For non-1500 cores
  dict append allowed_testmodes FULLSCAN                       FULLSCAN_INTERNAL
  dict append allowed_testmodes FULLSCAN_OPCG                  FULLSCAN_INTERNAL
  
  
  # Test mode reporting options
  #-------------------------------------------------------------------------------
  set_option reportscanchain                  all
  
  set_option reportchannelio                  yes
  set_option reportchannelmaskchain           yes
  set_option reportchannelmaskstate           yes
  
  set_option reportopcgregisters              yes
  
  # Test vector options
  #-------------------------------------------------------------------------------
  if {[get_feature -feature full_atpg]} {
      set_option maxpatterns                  500
  } else {
      set_option maxpatterns                  5
  }
  set_option maxglobalcoveragestatic          99.00
  set_option maxglobalcoveragedynamic         80.00
  
  set_option language                         stil
  set_option combinesections                  no
  set_option includemodeinit                  yes

}
