
//input ports
add mapped point clk_i clk_i -type PI PI
add mapped point rst_ni rst_ni -type PI PI
add mapped point operand_a_data_i[31] operand_a_data_i[31] -type PI PI
add mapped point operand_a_data_i[30] operand_a_data_i[30] -type PI PI
add mapped point operand_a_data_i[29] operand_a_data_i[29] -type PI PI
add mapped point operand_a_data_i[28] operand_a_data_i[28] -type PI PI
add mapped point operand_a_data_i[27] operand_a_data_i[27] -type PI PI
add mapped point operand_a_data_i[26] operand_a_data_i[26] -type PI PI
add mapped point operand_a_data_i[25] operand_a_data_i[25] -type PI PI
add mapped point operand_a_data_i[24] operand_a_data_i[24] -type PI PI
add mapped point operand_a_data_i[23] operand_a_data_i[23] -type PI PI
add mapped point operand_a_data_i[22] operand_a_data_i[22] -type PI PI
add mapped point operand_a_data_i[21] operand_a_data_i[21] -type PI PI
add mapped point operand_a_data_i[20] operand_a_data_i[20] -type PI PI
add mapped point operand_a_data_i[19] operand_a_data_i[19] -type PI PI
add mapped point operand_a_data_i[18] operand_a_data_i[18] -type PI PI
add mapped point operand_a_data_i[17] operand_a_data_i[17] -type PI PI
add mapped point operand_a_data_i[16] operand_a_data_i[16] -type PI PI
add mapped point operand_a_data_i[15] operand_a_data_i[15] -type PI PI
add mapped point operand_a_data_i[14] operand_a_data_i[14] -type PI PI
add mapped point operand_a_data_i[13] operand_a_data_i[13] -type PI PI
add mapped point operand_a_data_i[12] operand_a_data_i[12] -type PI PI
add mapped point operand_a_data_i[11] operand_a_data_i[11] -type PI PI
add mapped point operand_a_data_i[10] operand_a_data_i[10] -type PI PI
add mapped point operand_a_data_i[9] operand_a_data_i[9] -type PI PI
add mapped point operand_a_data_i[8] operand_a_data_i[8] -type PI PI
add mapped point operand_a_data_i[7] operand_a_data_i[7] -type PI PI
add mapped point operand_a_data_i[6] operand_a_data_i[6] -type PI PI
add mapped point operand_a_data_i[5] operand_a_data_i[5] -type PI PI
add mapped point operand_a_data_i[4] operand_a_data_i[4] -type PI PI
add mapped point operand_a_data_i[3] operand_a_data_i[3] -type PI PI
add mapped point operand_a_data_i[2] operand_a_data_i[2] -type PI PI
add mapped point operand_a_data_i[1] operand_a_data_i[1] -type PI PI
add mapped point operand_a_data_i[0] operand_a_data_i[0] -type PI PI
add mapped point operand_b_data_i[31] operand_b_data_i[31] -type PI PI
add mapped point operand_b_data_i[30] operand_b_data_i[30] -type PI PI
add mapped point operand_b_data_i[29] operand_b_data_i[29] -type PI PI
add mapped point operand_b_data_i[28] operand_b_data_i[28] -type PI PI
add mapped point operand_b_data_i[27] operand_b_data_i[27] -type PI PI
add mapped point operand_b_data_i[26] operand_b_data_i[26] -type PI PI
add mapped point operand_b_data_i[25] operand_b_data_i[25] -type PI PI
add mapped point operand_b_data_i[24] operand_b_data_i[24] -type PI PI
add mapped point operand_b_data_i[23] operand_b_data_i[23] -type PI PI
add mapped point operand_b_data_i[22] operand_b_data_i[22] -type PI PI
add mapped point operand_b_data_i[21] operand_b_data_i[21] -type PI PI
add mapped point operand_b_data_i[20] operand_b_data_i[20] -type PI PI
add mapped point operand_b_data_i[19] operand_b_data_i[19] -type PI PI
add mapped point operand_b_data_i[18] operand_b_data_i[18] -type PI PI
add mapped point operand_b_data_i[17] operand_b_data_i[17] -type PI PI
add mapped point operand_b_data_i[16] operand_b_data_i[16] -type PI PI
add mapped point operand_b_data_i[15] operand_b_data_i[15] -type PI PI
add mapped point operand_b_data_i[14] operand_b_data_i[14] -type PI PI
add mapped point operand_b_data_i[13] operand_b_data_i[13] -type PI PI
add mapped point operand_b_data_i[12] operand_b_data_i[12] -type PI PI
add mapped point operand_b_data_i[11] operand_b_data_i[11] -type PI PI
add mapped point operand_b_data_i[10] operand_b_data_i[10] -type PI PI
add mapped point operand_b_data_i[9] operand_b_data_i[9] -type PI PI
add mapped point operand_b_data_i[8] operand_b_data_i[8] -type PI PI
add mapped point operand_b_data_i[7] operand_b_data_i[7] -type PI PI
add mapped point operand_b_data_i[6] operand_b_data_i[6] -type PI PI
add mapped point operand_b_data_i[5] operand_b_data_i[5] -type PI PI
add mapped point operand_b_data_i[4] operand_b_data_i[4] -type PI PI
add mapped point operand_b_data_i[3] operand_b_data_i[3] -type PI PI
add mapped point operand_b_data_i[2] operand_b_data_i[2] -type PI PI
add mapped point operand_b_data_i[1] operand_b_data_i[1] -type PI PI
add mapped point operand_b_data_i[0] operand_b_data_i[0] -type PI PI
add mapped point operand_a_addr_i[7] operand_a_addr_i[7] -type PI PI
add mapped point operand_a_addr_i[6] operand_a_addr_i[6] -type PI PI
add mapped point operand_a_addr_i[5] operand_a_addr_i[5] -type PI PI
add mapped point operand_a_addr_i[4] operand_a_addr_i[4] -type PI PI
add mapped point operand_a_addr_i[3] operand_a_addr_i[3] -type PI PI
add mapped point operand_a_addr_i[2] operand_a_addr_i[2] -type PI PI
add mapped point operand_a_addr_i[1] operand_a_addr_i[1] -type PI PI
add mapped point operand_a_addr_i[0] operand_a_addr_i[0] -type PI PI
add mapped point operand_b_addr_i[7] operand_b_addr_i[7] -type PI PI
add mapped point operand_b_addr_i[6] operand_b_addr_i[6] -type PI PI
add mapped point operand_b_addr_i[5] operand_b_addr_i[5] -type PI PI
add mapped point operand_b_addr_i[4] operand_b_addr_i[4] -type PI PI
add mapped point operand_b_addr_i[3] operand_b_addr_i[3] -type PI PI
add mapped point operand_b_addr_i[2] operand_b_addr_i[2] -type PI PI
add mapped point operand_b_addr_i[1] operand_b_addr_i[1] -type PI PI
add mapped point operand_b_addr_i[0] operand_b_addr_i[0] -type PI PI
add mapped point operand_a_offset_i[31] operand_a_offset_i[31] -type PI PI
add mapped point operand_a_offset_i[30] operand_a_offset_i[30] -type PI PI
add mapped point operand_a_offset_i[29] operand_a_offset_i[29] -type PI PI
add mapped point operand_a_offset_i[28] operand_a_offset_i[28] -type PI PI
add mapped point operand_a_offset_i[27] operand_a_offset_i[27] -type PI PI
add mapped point operand_a_offset_i[26] operand_a_offset_i[26] -type PI PI
add mapped point operand_a_offset_i[25] operand_a_offset_i[25] -type PI PI
add mapped point operand_a_offset_i[24] operand_a_offset_i[24] -type PI PI
add mapped point operand_a_offset_i[23] operand_a_offset_i[23] -type PI PI
add mapped point operand_a_offset_i[22] operand_a_offset_i[22] -type PI PI
add mapped point operand_a_offset_i[21] operand_a_offset_i[21] -type PI PI
add mapped point operand_a_offset_i[20] operand_a_offset_i[20] -type PI PI
add mapped point operand_a_offset_i[19] operand_a_offset_i[19] -type PI PI
add mapped point operand_a_offset_i[18] operand_a_offset_i[18] -type PI PI
add mapped point operand_a_offset_i[17] operand_a_offset_i[17] -type PI PI
add mapped point operand_a_offset_i[16] operand_a_offset_i[16] -type PI PI
add mapped point operand_a_offset_i[15] operand_a_offset_i[15] -type PI PI
add mapped point operand_a_offset_i[14] operand_a_offset_i[14] -type PI PI
add mapped point operand_a_offset_i[13] operand_a_offset_i[13] -type PI PI
add mapped point operand_a_offset_i[12] operand_a_offset_i[12] -type PI PI
add mapped point operand_a_offset_i[11] operand_a_offset_i[11] -type PI PI
add mapped point operand_a_offset_i[10] operand_a_offset_i[10] -type PI PI
add mapped point operand_a_offset_i[9] operand_a_offset_i[9] -type PI PI
add mapped point operand_a_offset_i[8] operand_a_offset_i[8] -type PI PI
add mapped point operand_a_offset_i[7] operand_a_offset_i[7] -type PI PI
add mapped point operand_a_offset_i[6] operand_a_offset_i[6] -type PI PI
add mapped point operand_a_offset_i[5] operand_a_offset_i[5] -type PI PI
add mapped point operand_a_offset_i[4] operand_a_offset_i[4] -type PI PI
add mapped point operand_a_offset_i[3] operand_a_offset_i[3] -type PI PI
add mapped point operand_a_offset_i[2] operand_a_offset_i[2] -type PI PI
add mapped point operand_a_offset_i[1] operand_a_offset_i[1] -type PI PI
add mapped point operand_a_offset_i[0] operand_a_offset_i[0] -type PI PI
add mapped point operand_b_offset_i[31] operand_b_offset_i[31] -type PI PI
add mapped point operand_b_offset_i[30] operand_b_offset_i[30] -type PI PI
add mapped point operand_b_offset_i[29] operand_b_offset_i[29] -type PI PI
add mapped point operand_b_offset_i[28] operand_b_offset_i[28] -type PI PI
add mapped point operand_b_offset_i[27] operand_b_offset_i[27] -type PI PI
add mapped point operand_b_offset_i[26] operand_b_offset_i[26] -type PI PI
add mapped point operand_b_offset_i[25] operand_b_offset_i[25] -type PI PI
add mapped point operand_b_offset_i[24] operand_b_offset_i[24] -type PI PI
add mapped point operand_b_offset_i[23] operand_b_offset_i[23] -type PI PI
add mapped point operand_b_offset_i[22] operand_b_offset_i[22] -type PI PI
add mapped point operand_b_offset_i[21] operand_b_offset_i[21] -type PI PI
add mapped point operand_b_offset_i[20] operand_b_offset_i[20] -type PI PI
add mapped point operand_b_offset_i[19] operand_b_offset_i[19] -type PI PI
add mapped point operand_b_offset_i[18] operand_b_offset_i[18] -type PI PI
add mapped point operand_b_offset_i[17] operand_b_offset_i[17] -type PI PI
add mapped point operand_b_offset_i[16] operand_b_offset_i[16] -type PI PI
add mapped point operand_b_offset_i[15] operand_b_offset_i[15] -type PI PI
add mapped point operand_b_offset_i[14] operand_b_offset_i[14] -type PI PI
add mapped point operand_b_offset_i[13] operand_b_offset_i[13] -type PI PI
add mapped point operand_b_offset_i[12] operand_b_offset_i[12] -type PI PI
add mapped point operand_b_offset_i[11] operand_b_offset_i[11] -type PI PI
add mapped point operand_b_offset_i[10] operand_b_offset_i[10] -type PI PI
add mapped point operand_b_offset_i[9] operand_b_offset_i[9] -type PI PI
add mapped point operand_b_offset_i[8] operand_b_offset_i[8] -type PI PI
add mapped point operand_b_offset_i[7] operand_b_offset_i[7] -type PI PI
add mapped point operand_b_offset_i[6] operand_b_offset_i[6] -type PI PI
add mapped point operand_b_offset_i[5] operand_b_offset_i[5] -type PI PI
add mapped point operand_b_offset_i[4] operand_b_offset_i[4] -type PI PI
add mapped point operand_b_offset_i[3] operand_b_offset_i[3] -type PI PI
add mapped point operand_b_offset_i[2] operand_b_offset_i[2] -type PI PI
add mapped point operand_b_offset_i[1] operand_b_offset_i[1] -type PI PI
add mapped point operand_b_offset_i[0] operand_b_offset_i[0] -type PI PI
add mapped point re_a_i re_a_i -type PI PI
add mapped point re_b_i re_b_i -type PI PI
add mapped point we_a_i we_a_i -type PI PI
add mapped point we_b_i we_b_i -type PI PI

//output ports
add mapped point result_o[63] result_o[63] -type PO PO
add mapped point result_o[62] result_o[62] -type PO PO
add mapped point result_o[61] result_o[61] -type PO PO
add mapped point result_o[60] result_o[60] -type PO PO
add mapped point result_o[59] result_o[59] -type PO PO
add mapped point result_o[58] result_o[58] -type PO PO
add mapped point result_o[57] result_o[57] -type PO PO
add mapped point result_o[56] result_o[56] -type PO PO
add mapped point result_o[55] result_o[55] -type PO PO
add mapped point result_o[54] result_o[54] -type PO PO
add mapped point result_o[53] result_o[53] -type PO PO
add mapped point result_o[52] result_o[52] -type PO PO
add mapped point result_o[51] result_o[51] -type PO PO
add mapped point result_o[50] result_o[50] -type PO PO
add mapped point result_o[49] result_o[49] -type PO PO
add mapped point result_o[48] result_o[48] -type PO PO
add mapped point result_o[47] result_o[47] -type PO PO
add mapped point result_o[46] result_o[46] -type PO PO
add mapped point result_o[45] result_o[45] -type PO PO
add mapped point result_o[44] result_o[44] -type PO PO
add mapped point result_o[43] result_o[43] -type PO PO
add mapped point result_o[42] result_o[42] -type PO PO
add mapped point result_o[41] result_o[41] -type PO PO
add mapped point result_o[40] result_o[40] -type PO PO
add mapped point result_o[39] result_o[39] -type PO PO
add mapped point result_o[38] result_o[38] -type PO PO
add mapped point result_o[37] result_o[37] -type PO PO
add mapped point result_o[36] result_o[36] -type PO PO
add mapped point result_o[35] result_o[35] -type PO PO
add mapped point result_o[34] result_o[34] -type PO PO
add mapped point result_o[33] result_o[33] -type PO PO
add mapped point result_o[32] result_o[32] -type PO PO
add mapped point result_o[31] result_o[31] -type PO PO
add mapped point result_o[30] result_o[30] -type PO PO
add mapped point result_o[29] result_o[29] -type PO PO
add mapped point result_o[28] result_o[28] -type PO PO
add mapped point result_o[27] result_o[27] -type PO PO
add mapped point result_o[26] result_o[26] -type PO PO
add mapped point result_o[25] result_o[25] -type PO PO
add mapped point result_o[24] result_o[24] -type PO PO
add mapped point result_o[23] result_o[23] -type PO PO
add mapped point result_o[22] result_o[22] -type PO PO
add mapped point result_o[21] result_o[21] -type PO PO
add mapped point result_o[20] result_o[20] -type PO PO
add mapped point result_o[19] result_o[19] -type PO PO
add mapped point result_o[18] result_o[18] -type PO PO
add mapped point result_o[17] result_o[17] -type PO PO
add mapped point result_o[16] result_o[16] -type PO PO
add mapped point result_o[15] result_o[15] -type PO PO
add mapped point result_o[14] result_o[14] -type PO PO
add mapped point result_o[13] result_o[13] -type PO PO
add mapped point result_o[12] result_o[12] -type PO PO
add mapped point result_o[11] result_o[11] -type PO PO
add mapped point result_o[10] result_o[10] -type PO PO
add mapped point result_o[9] result_o[9] -type PO PO
add mapped point result_o[8] result_o[8] -type PO PO
add mapped point result_o[7] result_o[7] -type PO PO
add mapped point result_o[6] result_o[6] -type PO PO
add mapped point result_o[5] result_o[5] -type PO PO
add mapped point result_o[4] result_o[4] -type PO PO
add mapped point result_o[3] result_o[3] -type PO PO
add mapped point result_o[2] result_o[2] -type PO PO
add mapped point result_o[1] result_o[1] -type PO PO
add mapped point result_o[0] result_o[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point i_clk_divider/inst_SDFFRX4/Q i_clk_divider/inst_SDFFRX4/Q -type DFF DFF
add mapped point i_clk_divider/inst_SDFFRX4/QN i_clk_divider/inst_SDFFRX4/QN -type DFF DFF
add mapped point i_rst_sync1/inst_SDFFRX4/Q i_rst_sync1/inst_SDFFRX4/Q -type DFF DFF
add mapped point i_rst_sync1/inst_SDFFRX4/QN i_rst_sync1/inst_SDFFRX4/QN -type DFF DFF
add mapped point i_rst_sync2/inst_SDFFRX4/Q i_rst_sync2/inst_SDFFRX4/Q -type DFF DFF
add mapped point i_rst_sync2/inst_SDFFRX4/QN i_rst_sync2/inst_SDFFRX4/QN -type DFF DFF
add mapped point mem_a_addr[0][0]/q mem_a_addr_reg_0_0/Q -type DFF DFF
add mapped point mem_a_addr[0][1]/q mem_a_addr_reg_0_1/Q -type DFF DFF
add mapped point mem_a_addr[0][2]/q mem_a_addr_reg_0_2/Q -type DFF DFF
add mapped point mem_a_addr[0][3]/q mem_a_addr_reg_0_3/Q -type DFF DFF
add mapped point mem_a_addr[0][4]/q mem_a_addr_reg_0_4/Q -type DFF DFF
add mapped point mem_a_addr[0][5]/q mem_a_addr_reg_0_5/Q -type DFF DFF
add mapped point mem_a_addr[0][6]/q mem_a_addr_reg_0_6/Q -type DFF DFF
add mapped point mem_a_addr[0][7]/q mem_a_addr_reg_0_7/Q -type DFF DFF
add mapped point mem_a_addr[1][0]/q mem_a_addr_reg_1_0/Q -type DFF DFF
add mapped point mem_a_addr[1][1]/q mem_a_addr_reg_1_1/Q -type DFF DFF
add mapped point mem_a_addr[1][2]/q mem_a_addr_reg_1_2/Q -type DFF DFF
add mapped point mem_a_addr[1][3]/q mem_a_addr_reg_1_3/Q -type DFF DFF
add mapped point mem_a_addr[1][4]/q mem_a_addr_reg_1_4/Q -type DFF DFF
add mapped point mem_a_addr[1][5]/q mem_a_addr_reg_1_5/Q -type DFF DFF
add mapped point mem_a_addr[1][6]/q mem_a_addr_reg_1_6/Q -type DFF DFF
add mapped point mem_a_addr[1][7]/q mem_a_addr_reg_1_7/Q -type DFF DFF
add mapped point mem_a_addr[2][0]/q mem_a_addr_reg_2_0/Q -type DFF DFF
add mapped point mem_a_addr[2][1]/q mem_a_addr_reg_2_1/Q -type DFF DFF
add mapped point mem_a_addr[2][2]/q mem_a_addr_reg_2_2/Q -type DFF DFF
add mapped point mem_a_addr[2][3]/q mem_a_addr_reg_2_3/Q -type DFF DFF
add mapped point mem_a_addr[2][4]/q mem_a_addr_reg_2_4/Q -type DFF DFF
add mapped point mem_a_addr[2][5]/q mem_a_addr_reg_2_5/Q -type DFF DFF
add mapped point mem_a_addr[2][6]/q mem_a_addr_reg_2_6/Q -type DFF DFF
add mapped point mem_a_addr[2][7]/q mem_a_addr_reg_2_7/Q -type DFF DFF
add mapped point mem_a_addr[3][0]/q mem_a_addr_reg_3_0/Q -type DFF DFF
add mapped point mem_a_addr[3][1]/q mem_a_addr_reg_3_1/Q -type DFF DFF
add mapped point mem_a_addr[3][2]/q mem_a_addr_reg_3_2/Q -type DFF DFF
add mapped point mem_a_addr[3][3]/q mem_a_addr_reg_3_3/Q -type DFF DFF
add mapped point mem_a_addr[3][4]/q mem_a_addr_reg_3_4/Q -type DFF DFF
add mapped point mem_a_addr[3][5]/q mem_a_addr_reg_3_5/Q -type DFF DFF
add mapped point mem_a_addr[3][6]/q mem_a_addr_reg_3_6/Q -type DFF DFF
add mapped point mem_a_addr[3][7]/q mem_a_addr_reg_3_7/Q -type DFF DFF
add mapped point mem_a_addr[4][0]/q mem_a_addr_reg_4_0/Q -type DFF DFF
add mapped point mem_a_addr[4][1]/q mem_a_addr_reg_4_1/Q -type DFF DFF
add mapped point mem_a_addr[4][2]/q mem_a_addr_reg_4_2/Q -type DFF DFF
add mapped point mem_a_addr[4][3]/q mem_a_addr_reg_4_3/Q -type DFF DFF
add mapped point mem_a_addr[4][4]/q mem_a_addr_reg_4_4/Q -type DFF DFF
add mapped point mem_a_addr[4][5]/q mem_a_addr_reg_4_5/Q -type DFF DFF
add mapped point mem_a_addr[4][6]/q mem_a_addr_reg_4_6/Q -type DFF DFF
add mapped point mem_a_addr[4][7]/q mem_a_addr_reg_4_7/Q -type DFF DFF
add mapped point mem_a_addr[5][0]/q mem_a_addr_reg_5_0/Q -type DFF DFF
add mapped point mem_a_addr[5][1]/q mem_a_addr_reg_5_1/Q -type DFF DFF
add mapped point mem_a_addr[5][2]/q mem_a_addr_reg_5_2/Q -type DFF DFF
add mapped point mem_a_addr[5][3]/q mem_a_addr_reg_5_3/Q -type DFF DFF
add mapped point mem_a_addr[5][4]/q mem_a_addr_reg_5_4/Q -type DFF DFF
add mapped point mem_a_addr[5][5]/q mem_a_addr_reg_5_5/Q -type DFF DFF
add mapped point mem_a_addr[5][6]/q mem_a_addr_reg_5_6/Q -type DFF DFF
add mapped point mem_a_addr[5][7]/q mem_a_addr_reg_5_7/Q -type DFF DFF
add mapped point mem_a_addr[6][0]/q mem_a_addr_reg_6_0/Q -type DFF DFF
add mapped point mem_a_addr[6][1]/q mem_a_addr_reg_6_1/Q -type DFF DFF
add mapped point mem_a_addr[6][2]/q mem_a_addr_reg_6_2/Q -type DFF DFF
add mapped point mem_a_addr[6][3]/q mem_a_addr_reg_6_3/Q -type DFF DFF
add mapped point mem_a_addr[6][4]/q mem_a_addr_reg_6_4/Q -type DFF DFF
add mapped point mem_a_addr[6][5]/q mem_a_addr_reg_6_5/Q -type DFF DFF
add mapped point mem_a_addr[6][6]/q mem_a_addr_reg_6_6/Q -type DFF DFF
add mapped point mem_a_addr[6][7]/q mem_a_addr_reg_6_7/Q -type DFF DFF
add mapped point mem_a_addr[7][0]/q mem_a_addr_reg_7_0/Q -type DFF DFF
add mapped point mem_a_addr[7][1]/q mem_a_addr_reg_7_1/Q -type DFF DFF
add mapped point mem_a_addr[7][2]/q mem_a_addr_reg_7_2/Q -type DFF DFF
add mapped point mem_a_addr[7][3]/q mem_a_addr_reg_7_3/Q -type DFF DFF
add mapped point mem_a_addr[7][4]/q mem_a_addr_reg_7_4/Q -type DFF DFF
add mapped point mem_a_addr[7][5]/q mem_a_addr_reg_7_5/Q -type DFF DFF
add mapped point mem_a_addr[7][6]/q mem_a_addr_reg_7_6/Q -type DFF DFF
add mapped point mem_a_addr[7][7]/q mem_a_addr_reg_7_7/Q -type DFF DFF
add mapped point mem_a_addr[8][0]/q mem_a_addr_reg_8_0/Q -type DFF DFF
add mapped point mem_a_addr[8][1]/q mem_a_addr_reg_8_1/Q -type DFF DFF
add mapped point mem_a_addr[8][2]/q mem_a_addr_reg_8_2/Q -type DFF DFF
add mapped point mem_a_addr[8][3]/q mem_a_addr_reg_8_3/Q -type DFF DFF
add mapped point mem_a_addr[8][4]/q mem_a_addr_reg_8_4/Q -type DFF DFF
add mapped point mem_a_addr[8][5]/q mem_a_addr_reg_8_5/Q -type DFF DFF
add mapped point mem_a_addr[8][6]/q mem_a_addr_reg_8_6/Q -type DFF DFF
add mapped point mem_a_addr[8][7]/q mem_a_addr_reg_8_7/Q -type DFF DFF
add mapped point mem_a_addr[9][0]/q mem_a_addr_reg_9_0/Q -type DFF DFF
add mapped point mem_a_addr[9][1]/q mem_a_addr_reg_9_1/Q -type DFF DFF
add mapped point mem_a_addr[9][2]/q mem_a_addr_reg_9_2/Q -type DFF DFF
add mapped point mem_a_addr[9][3]/q mem_a_addr_reg_9_3/Q -type DFF DFF
add mapped point mem_a_addr[9][4]/q mem_a_addr_reg_9_4/Q -type DFF DFF
add mapped point mem_a_addr[9][5]/q mem_a_addr_reg_9_5/Q -type DFF DFF
add mapped point mem_a_addr[9][6]/q mem_a_addr_reg_9_6/Q -type DFF DFF
add mapped point mem_a_addr[9][7]/q mem_a_addr_reg_9_7/Q -type DFF DFF
add mapped point mem_a_addr[10][0]/q mem_a_addr_reg_10_0/Q -type DFF DFF
add mapped point mem_a_addr[10][1]/q mem_a_addr_reg_10_1/Q -type DFF DFF
add mapped point mem_a_addr[10][2]/q mem_a_addr_reg_10_2/Q -type DFF DFF
add mapped point mem_a_addr[10][3]/q mem_a_addr_reg_10_3/Q -type DFF DFF
add mapped point mem_a_addr[10][4]/q mem_a_addr_reg_10_4/Q -type DFF DFF
add mapped point mem_a_addr[10][5]/q mem_a_addr_reg_10_5/Q -type DFF DFF
add mapped point mem_a_addr[10][6]/q mem_a_addr_reg_10_6/Q -type DFF DFF
add mapped point mem_a_addr[10][7]/q mem_a_addr_reg_10_7/Q -type DFF DFF
add mapped point mem_a_addr[11][0]/q mem_a_addr_reg_11_0/Q -type DFF DFF
add mapped point mem_a_addr[11][1]/q mem_a_addr_reg_11_1/Q -type DFF DFF
add mapped point mem_a_addr[11][2]/q mem_a_addr_reg_11_2/Q -type DFF DFF
add mapped point mem_a_addr[11][3]/q mem_a_addr_reg_11_3/Q -type DFF DFF
add mapped point mem_a_addr[11][4]/q mem_a_addr_reg_11_4/Q -type DFF DFF
add mapped point mem_a_addr[11][5]/q mem_a_addr_reg_11_5/Q -type DFF DFF
add mapped point mem_a_addr[11][6]/q mem_a_addr_reg_11_6/Q -type DFF DFF
add mapped point mem_a_addr[11][7]/q mem_a_addr_reg_11_7/Q -type DFF DFF
add mapped point mem_a_addr[12][0]/q mem_a_addr_reg_12_0/Q -type DFF DFF
add mapped point mem_a_addr[12][1]/q mem_a_addr_reg_12_1/Q -type DFF DFF
add mapped point mem_a_addr[12][2]/q mem_a_addr_reg_12_2/Q -type DFF DFF
add mapped point mem_a_addr[12][3]/q mem_a_addr_reg_12_3/Q -type DFF DFF
add mapped point mem_a_addr[12][4]/q mem_a_addr_reg_12_4/Q -type DFF DFF
add mapped point mem_a_addr[12][5]/q mem_a_addr_reg_12_5/Q -type DFF DFF
add mapped point mem_a_addr[12][6]/q mem_a_addr_reg_12_6/Q -type DFF DFF
add mapped point mem_a_addr[12][7]/q mem_a_addr_reg_12_7/Q -type DFF DFF
add mapped point mem_a_addr[13][0]/q mem_a_addr_reg_13_0/Q -type DFF DFF
add mapped point mem_a_addr[13][1]/q mem_a_addr_reg_13_1/Q -type DFF DFF
add mapped point mem_a_addr[13][2]/q mem_a_addr_reg_13_2/Q -type DFF DFF
add mapped point mem_a_addr[13][3]/q mem_a_addr_reg_13_3/Q -type DFF DFF
add mapped point mem_a_addr[13][4]/q mem_a_addr_reg_13_4/Q -type DFF DFF
add mapped point mem_a_addr[13][5]/q mem_a_addr_reg_13_5/Q -type DFF DFF
add mapped point mem_a_addr[13][6]/q mem_a_addr_reg_13_6/Q -type DFF DFF
add mapped point mem_a_addr[13][7]/q mem_a_addr_reg_13_7/Q -type DFF DFF
add mapped point mem_a_addr[14][0]/q mem_a_addr_reg_14_0/Q -type DFF DFF
add mapped point mem_a_addr[14][1]/q mem_a_addr_reg_14_1/Q -type DFF DFF
add mapped point mem_a_addr[14][2]/q mem_a_addr_reg_14_2/Q -type DFF DFF
add mapped point mem_a_addr[14][3]/q mem_a_addr_reg_14_3/Q -type DFF DFF
add mapped point mem_a_addr[14][4]/q mem_a_addr_reg_14_4/Q -type DFF DFF
add mapped point mem_a_addr[14][5]/q mem_a_addr_reg_14_5/Q -type DFF DFF
add mapped point mem_a_addr[14][6]/q mem_a_addr_reg_14_6/Q -type DFF DFF
add mapped point mem_a_addr[14][7]/q mem_a_addr_reg_14_7/Q -type DFF DFF
add mapped point mem_a_addr[15][0]/q mem_a_addr_reg_15_0/Q -type DFF DFF
add mapped point mem_a_addr[15][1]/q mem_a_addr_reg_15_1/Q -type DFF DFF
add mapped point mem_a_addr[15][2]/q mem_a_addr_reg_15_2/Q -type DFF DFF
add mapped point mem_a_addr[15][3]/q mem_a_addr_reg_15_3/Q -type DFF DFF
add mapped point mem_a_addr[15][4]/q mem_a_addr_reg_15_4/Q -type DFF DFF
add mapped point mem_a_addr[15][5]/q mem_a_addr_reg_15_5/Q -type DFF DFF
add mapped point mem_a_addr[15][6]/q mem_a_addr_reg_15_6/Q -type DFF DFF
add mapped point mem_a_addr[15][7]/q mem_a_addr_reg_15_7/Q -type DFF DFF
add mapped point mem_b_addr[0][0]/q mem_b_addr_reg_0_0/Q -type DFF DFF
add mapped point mem_b_addr[0][1]/q mem_b_addr_reg_0_1/Q -type DFF DFF
add mapped point mem_b_addr[0][2]/q mem_b_addr_reg_0_2/Q -type DFF DFF
add mapped point mem_b_addr[0][3]/q mem_b_addr_reg_0_3/Q -type DFF DFF
add mapped point mem_b_addr[0][4]/q mem_b_addr_reg_0_4/Q -type DFF DFF
add mapped point mem_b_addr[0][5]/q mem_b_addr_reg_0_5/Q -type DFF DFF
add mapped point mem_b_addr[0][6]/q mem_b_addr_reg_0_6/Q -type DFF DFF
add mapped point mem_b_addr[0][7]/q mem_b_addr_reg_0_7/Q -type DFF DFF
add mapped point mem_b_addr[1][0]/q mem_b_addr_reg_1_0/Q -type DFF DFF
add mapped point mem_b_addr[1][1]/q mem_b_addr_reg_1_1/Q -type DFF DFF
add mapped point mem_b_addr[1][2]/q mem_b_addr_reg_1_2/Q -type DFF DFF
add mapped point mem_b_addr[1][3]/q mem_b_addr_reg_1_3/Q -type DFF DFF
add mapped point mem_b_addr[1][4]/q mem_b_addr_reg_1_4/Q -type DFF DFF
add mapped point mem_b_addr[1][5]/q mem_b_addr_reg_1_5/Q -type DFF DFF
add mapped point mem_b_addr[1][6]/q mem_b_addr_reg_1_6/Q -type DFF DFF
add mapped point mem_b_addr[1][7]/q mem_b_addr_reg_1_7/Q -type DFF DFF
add mapped point mem_b_addr[2][0]/q mem_b_addr_reg_2_0/Q -type DFF DFF
add mapped point mem_b_addr[2][1]/q mem_b_addr_reg_2_1/Q -type DFF DFF
add mapped point mem_b_addr[2][2]/q mem_b_addr_reg_2_2/Q -type DFF DFF
add mapped point mem_b_addr[2][3]/q mem_b_addr_reg_2_3/Q -type DFF DFF
add mapped point mem_b_addr[2][4]/q mem_b_addr_reg_2_4/Q -type DFF DFF
add mapped point mem_b_addr[2][5]/q mem_b_addr_reg_2_5/Q -type DFF DFF
add mapped point mem_b_addr[2][6]/q mem_b_addr_reg_2_6/Q -type DFF DFF
add mapped point mem_b_addr[2][7]/q mem_b_addr_reg_2_7/Q -type DFF DFF
add mapped point mem_b_addr[3][0]/q mem_b_addr_reg_3_0/Q -type DFF DFF
add mapped point mem_b_addr[3][1]/q mem_b_addr_reg_3_1/Q -type DFF DFF
add mapped point mem_b_addr[3][2]/q mem_b_addr_reg_3_2/Q -type DFF DFF
add mapped point mem_b_addr[3][3]/q mem_b_addr_reg_3_3/Q -type DFF DFF
add mapped point mem_b_addr[3][4]/q mem_b_addr_reg_3_4/Q -type DFF DFF
add mapped point mem_b_addr[3][5]/q mem_b_addr_reg_3_5/Q -type DFF DFF
add mapped point mem_b_addr[3][6]/q mem_b_addr_reg_3_6/Q -type DFF DFF
add mapped point mem_b_addr[3][7]/q mem_b_addr_reg_3_7/Q -type DFF DFF
add mapped point mem_b_addr[4][0]/q mem_b_addr_reg_4_0/Q -type DFF DFF
add mapped point mem_b_addr[4][1]/q mem_b_addr_reg_4_1/Q -type DFF DFF
add mapped point mem_b_addr[4][2]/q mem_b_addr_reg_4_2/Q -type DFF DFF
add mapped point mem_b_addr[4][3]/q mem_b_addr_reg_4_3/Q -type DFF DFF
add mapped point mem_b_addr[4][4]/q mem_b_addr_reg_4_4/Q -type DFF DFF
add mapped point mem_b_addr[4][5]/q mem_b_addr_reg_4_5/Q -type DFF DFF
add mapped point mem_b_addr[4][6]/q mem_b_addr_reg_4_6/Q -type DFF DFF
add mapped point mem_b_addr[4][7]/q mem_b_addr_reg_4_7/Q -type DFF DFF
add mapped point mem_b_addr[5][0]/q mem_b_addr_reg_5_0/Q -type DFF DFF
add mapped point mem_b_addr[5][1]/q mem_b_addr_reg_5_1/Q -type DFF DFF
add mapped point mem_b_addr[5][2]/q mem_b_addr_reg_5_2/Q -type DFF DFF
add mapped point mem_b_addr[5][3]/q mem_b_addr_reg_5_3/Q -type DFF DFF
add mapped point mem_b_addr[5][4]/q mem_b_addr_reg_5_4/Q -type DFF DFF
add mapped point mem_b_addr[5][5]/q mem_b_addr_reg_5_5/Q -type DFF DFF
add mapped point mem_b_addr[5][6]/q mem_b_addr_reg_5_6/Q -type DFF DFF
add mapped point mem_b_addr[5][7]/q mem_b_addr_reg_5_7/Q -type DFF DFF
add mapped point mem_b_addr[6][0]/q mem_b_addr_reg_6_0/Q -type DFF DFF
add mapped point mem_b_addr[6][1]/q mem_b_addr_reg_6_1/Q -type DFF DFF
add mapped point mem_b_addr[6][2]/q mem_b_addr_reg_6_2/Q -type DFF DFF
add mapped point mem_b_addr[6][3]/q mem_b_addr_reg_6_3/Q -type DFF DFF
add mapped point mem_b_addr[6][4]/q mem_b_addr_reg_6_4/Q -type DFF DFF
add mapped point mem_b_addr[6][5]/q mem_b_addr_reg_6_5/Q -type DFF DFF
add mapped point mem_b_addr[6][6]/q mem_b_addr_reg_6_6/Q -type DFF DFF
add mapped point mem_b_addr[6][7]/q mem_b_addr_reg_6_7/Q -type DFF DFF
add mapped point mem_b_addr[7][0]/q mem_b_addr_reg_7_0/Q -type DFF DFF
add mapped point mem_b_addr[7][1]/q mem_b_addr_reg_7_1/Q -type DFF DFF
add mapped point mem_b_addr[7][2]/q mem_b_addr_reg_7_2/Q -type DFF DFF
add mapped point mem_b_addr[7][3]/q mem_b_addr_reg_7_3/Q -type DFF DFF
add mapped point mem_b_addr[7][4]/q mem_b_addr_reg_7_4/Q -type DFF DFF
add mapped point mem_b_addr[7][5]/q mem_b_addr_reg_7_5/Q -type DFF DFF
add mapped point mem_b_addr[7][6]/q mem_b_addr_reg_7_6/Q -type DFF DFF
add mapped point mem_b_addr[7][7]/q mem_b_addr_reg_7_7/Q -type DFF DFF
add mapped point mem_b_addr[8][0]/q mem_b_addr_reg_8_0/Q -type DFF DFF
add mapped point mem_b_addr[8][1]/q mem_b_addr_reg_8_1/Q -type DFF DFF
add mapped point mem_b_addr[8][2]/q mem_b_addr_reg_8_2/Q -type DFF DFF
add mapped point mem_b_addr[8][3]/q mem_b_addr_reg_8_3/Q -type DFF DFF
add mapped point mem_b_addr[8][4]/q mem_b_addr_reg_8_4/Q -type DFF DFF
add mapped point mem_b_addr[8][5]/q mem_b_addr_reg_8_5/Q -type DFF DFF
add mapped point mem_b_addr[8][6]/q mem_b_addr_reg_8_6/Q -type DFF DFF
add mapped point mem_b_addr[8][7]/q mem_b_addr_reg_8_7/Q -type DFF DFF
add mapped point mem_b_addr[9][0]/q mem_b_addr_reg_9_0/Q -type DFF DFF
add mapped point mem_b_addr[9][1]/q mem_b_addr_reg_9_1/Q -type DFF DFF
add mapped point mem_b_addr[9][2]/q mem_b_addr_reg_9_2/Q -type DFF DFF
add mapped point mem_b_addr[9][3]/q mem_b_addr_reg_9_3/Q -type DFF DFF
add mapped point mem_b_addr[9][4]/q mem_b_addr_reg_9_4/Q -type DFF DFF
add mapped point mem_b_addr[9][5]/q mem_b_addr_reg_9_5/Q -type DFF DFF
add mapped point mem_b_addr[9][6]/q mem_b_addr_reg_9_6/Q -type DFF DFF
add mapped point mem_b_addr[9][7]/q mem_b_addr_reg_9_7/Q -type DFF DFF
add mapped point mem_b_addr[10][0]/q mem_b_addr_reg_10_0/Q -type DFF DFF
add mapped point mem_b_addr[10][1]/q mem_b_addr_reg_10_1/Q -type DFF DFF
add mapped point mem_b_addr[10][2]/q mem_b_addr_reg_10_2/Q -type DFF DFF
add mapped point mem_b_addr[10][3]/q mem_b_addr_reg_10_3/Q -type DFF DFF
add mapped point mem_b_addr[10][4]/q mem_b_addr_reg_10_4/Q -type DFF DFF
add mapped point mem_b_addr[10][5]/q mem_b_addr_reg_10_5/Q -type DFF DFF
add mapped point mem_b_addr[10][6]/q mem_b_addr_reg_10_6/Q -type DFF DFF
add mapped point mem_b_addr[10][7]/q mem_b_addr_reg_10_7/Q -type DFF DFF
add mapped point mem_b_addr[11][0]/q mem_b_addr_reg_11_0/Q -type DFF DFF
add mapped point mem_b_addr[11][1]/q mem_b_addr_reg_11_1/Q -type DFF DFF
add mapped point mem_b_addr[11][2]/q mem_b_addr_reg_11_2/Q -type DFF DFF
add mapped point mem_b_addr[11][3]/q mem_b_addr_reg_11_3/Q -type DFF DFF
add mapped point mem_b_addr[11][4]/q mem_b_addr_reg_11_4/Q -type DFF DFF
add mapped point mem_b_addr[11][5]/q mem_b_addr_reg_11_5/Q -type DFF DFF
add mapped point mem_b_addr[11][6]/q mem_b_addr_reg_11_6/Q -type DFF DFF
add mapped point mem_b_addr[11][7]/q mem_b_addr_reg_11_7/Q -type DFF DFF
add mapped point mem_b_addr[12][0]/q mem_b_addr_reg_12_0/Q -type DFF DFF
add mapped point mem_b_addr[12][1]/q mem_b_addr_reg_12_1/Q -type DFF DFF
add mapped point mem_b_addr[12][2]/q mem_b_addr_reg_12_2/Q -type DFF DFF
add mapped point mem_b_addr[12][3]/q mem_b_addr_reg_12_3/Q -type DFF DFF
add mapped point mem_b_addr[12][4]/q mem_b_addr_reg_12_4/Q -type DFF DFF
add mapped point mem_b_addr[12][5]/q mem_b_addr_reg_12_5/Q -type DFF DFF
add mapped point mem_b_addr[12][6]/q mem_b_addr_reg_12_6/Q -type DFF DFF
add mapped point mem_b_addr[12][7]/q mem_b_addr_reg_12_7/Q -type DFF DFF
add mapped point mem_b_addr[13][0]/q mem_b_addr_reg_13_0/Q -type DFF DFF
add mapped point mem_b_addr[13][1]/q mem_b_addr_reg_13_1/Q -type DFF DFF
add mapped point mem_b_addr[13][2]/q mem_b_addr_reg_13_2/Q -type DFF DFF
add mapped point mem_b_addr[13][3]/q mem_b_addr_reg_13_3/Q -type DFF DFF
add mapped point mem_b_addr[13][4]/q mem_b_addr_reg_13_4/Q -type DFF DFF
add mapped point mem_b_addr[13][5]/q mem_b_addr_reg_13_5/Q -type DFF DFF
add mapped point mem_b_addr[13][6]/q mem_b_addr_reg_13_6/Q -type DFF DFF
add mapped point mem_b_addr[13][7]/q mem_b_addr_reg_13_7/Q -type DFF DFF
add mapped point mem_b_addr[14][0]/q mem_b_addr_reg_14_0/Q -type DFF DFF
add mapped point mem_b_addr[14][1]/q mem_b_addr_reg_14_1/Q -type DFF DFF
add mapped point mem_b_addr[14][2]/q mem_b_addr_reg_14_2/Q -type DFF DFF
add mapped point mem_b_addr[14][3]/q mem_b_addr_reg_14_3/Q -type DFF DFF
add mapped point mem_b_addr[14][4]/q mem_b_addr_reg_14_4/Q -type DFF DFF
add mapped point mem_b_addr[14][5]/q mem_b_addr_reg_14_5/Q -type DFF DFF
add mapped point mem_b_addr[14][6]/q mem_b_addr_reg_14_6/Q -type DFF DFF
add mapped point mem_b_addr[14][7]/q mem_b_addr_reg_14_7/Q -type DFF DFF
add mapped point mem_b_addr[15][0]/q mem_b_addr_reg_15_0/Q -type DFF DFF
add mapped point mem_b_addr[15][1]/q mem_b_addr_reg_15_1/Q -type DFF DFF
add mapped point mem_b_addr[15][2]/q mem_b_addr_reg_15_2/Q -type DFF DFF
add mapped point mem_b_addr[15][3]/q mem_b_addr_reg_15_3/Q -type DFF DFF
add mapped point mem_b_addr[15][4]/q mem_b_addr_reg_15_4/Q -type DFF DFF
add mapped point mem_b_addr[15][5]/q mem_b_addr_reg_15_5/Q -type DFF DFF
add mapped point mem_b_addr[15][6]/q mem_b_addr_reg_15_6/Q -type DFF DFF
add mapped point mem_b_addr[15][7]/q mem_b_addr_reg_15_7/Q -type DFF DFF
add mapped point mem_a_re[0]/q mem_a_re_reg_0/Q -type DFF DFF
add mapped point mem_a_re[1]/q mem_a_re_reg_1/Q -type DFF DFF
add mapped point mem_a_re[2]/q mem_a_re_reg_2/Q -type DFF DFF
add mapped point mem_a_re[3]/q mem_a_re_reg_3/Q -type DFF DFF
add mapped point mem_a_re[4]/q mem_a_re_reg_4/Q -type DFF DFF
add mapped point mem_a_re[5]/q mem_a_re_reg_5/Q -type DFF DFF
add mapped point mem_a_re[6]/q mem_a_re_reg_6/Q -type DFF DFF
add mapped point mem_a_re[7]/q mem_a_re_reg_7/Q -type DFF DFF
add mapped point mem_a_re[8]/q mem_a_re_reg_8/Q -type DFF DFF
add mapped point mem_a_re[9]/q mem_a_re_reg_9/Q -type DFF DFF
add mapped point mem_a_re[10]/q mem_a_re_reg_10/Q -type DFF DFF
add mapped point mem_a_re[11]/q mem_a_re_reg_11/Q -type DFF DFF
add mapped point mem_a_re[12]/q mem_a_re_reg_12/Q -type DFF DFF
add mapped point mem_a_re[13]/q mem_a_re_reg_13/Q -type DFF DFF
add mapped point mem_a_re[14]/q mem_a_re_reg_14/Q -type DFF DFF
add mapped point mem_a_re[15]/q mem_a_re_reg_15/Q -type DFF DFF
add mapped point mem_a_we[0]/q mem_a_we_reg_0/Q -type DFF DFF
add mapped point mem_a_we[1]/q mem_a_we_reg_1/Q -type DFF DFF
add mapped point mem_a_we[2]/q mem_a_we_reg_2/Q -type DFF DFF
add mapped point mem_a_we[3]/q mem_a_we_reg_3/Q -type DFF DFF
add mapped point mem_a_we[4]/q mem_a_we_reg_4/Q -type DFF DFF
add mapped point mem_a_we[5]/q mem_a_we_reg_5/Q -type DFF DFF
add mapped point mem_a_we[6]/q mem_a_we_reg_6/Q -type DFF DFF
add mapped point mem_a_we[7]/q mem_a_we_reg_7/Q -type DFF DFF
add mapped point mem_a_we[8]/q mem_a_we_reg_8/Q -type DFF DFF
add mapped point mem_a_we[9]/q mem_a_we_reg_9/Q -type DFF DFF
add mapped point mem_a_we[10]/q mem_a_we_reg_10/Q -type DFF DFF
add mapped point mem_a_we[11]/q mem_a_we_reg_11/Q -type DFF DFF
add mapped point mem_a_we[12]/q mem_a_we_reg_12/Q -type DFF DFF
add mapped point mem_a_we[13]/q mem_a_we_reg_13/Q -type DFF DFF
add mapped point mem_a_we[14]/q mem_a_we_reg_14/Q -type DFF DFF
add mapped point mem_a_we[15]/q mem_a_we_reg_15/Q -type DFF DFF
add mapped point mem_b_re[0]/q mem_b_re_reg_0/Q -type DFF DFF
add mapped point mem_b_re[1]/q mem_b_re_reg_1/Q -type DFF DFF
add mapped point mem_b_re[2]/q mem_b_re_reg_2/Q -type DFF DFF
add mapped point mem_b_re[3]/q mem_b_re_reg_3/Q -type DFF DFF
add mapped point mem_b_re[4]/q mem_b_re_reg_4/Q -type DFF DFF
add mapped point mem_b_re[5]/q mem_b_re_reg_5/Q -type DFF DFF
add mapped point mem_b_re[6]/q mem_b_re_reg_6/Q -type DFF DFF
add mapped point mem_b_re[7]/q mem_b_re_reg_7/Q -type DFF DFF
add mapped point mem_b_re[8]/q mem_b_re_reg_8/Q -type DFF DFF
add mapped point mem_b_re[9]/q mem_b_re_reg_9/Q -type DFF DFF
add mapped point mem_b_re[10]/q mem_b_re_reg_10/Q -type DFF DFF
add mapped point mem_b_re[11]/q mem_b_re_reg_11/Q -type DFF DFF
add mapped point mem_b_re[12]/q mem_b_re_reg_12/Q -type DFF DFF
add mapped point mem_b_re[13]/q mem_b_re_reg_13/Q -type DFF DFF
add mapped point mem_b_re[14]/q mem_b_re_reg_14/Q -type DFF DFF
add mapped point mem_b_re[15]/q mem_b_re_reg_15/Q -type DFF DFF
add mapped point mem_b_we[0]/q mem_b_we_reg_0/Q -type DFF DFF
add mapped point mem_b_we[1]/q mem_b_we_reg_1/Q -type DFF DFF
add mapped point mem_b_we[2]/q mem_b_we_reg_2/Q -type DFF DFF
add mapped point mem_b_we[3]/q mem_b_we_reg_3/Q -type DFF DFF
add mapped point mem_b_we[4]/q mem_b_we_reg_4/Q -type DFF DFF
add mapped point mem_b_we[5]/q mem_b_we_reg_5/Q -type DFF DFF
add mapped point mem_b_we[6]/q mem_b_we_reg_6/Q -type DFF DFF
add mapped point mem_b_we[7]/q mem_b_we_reg_7/Q -type DFF DFF
add mapped point mem_b_we[8]/q mem_b_we_reg_8/Q -type DFF DFF
add mapped point mem_b_we[9]/q mem_b_we_reg_9/Q -type DFF DFF
add mapped point mem_b_we[10]/q mem_b_we_reg_10/Q -type DFF DFF
add mapped point mem_b_we[11]/q mem_b_we_reg_11/Q -type DFF DFF
add mapped point mem_b_we[12]/q mem_b_we_reg_12/Q -type DFF DFF
add mapped point mem_b_we[13]/q mem_b_we_reg_13/Q -type DFF DFF
add mapped point mem_b_we[14]/q mem_b_we_reg_14/Q -type DFF DFF
add mapped point mem_b_we[15]/q mem_b_we_reg_15/Q -type DFF DFF



//Black Boxes
add mapped point genblk1[0].i_mem_a/i_ram genblk1_0_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[0].i_mem_b/i_ram genblk1_0_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[1].i_mem_a/i_ram genblk1_1_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[1].i_mem_b/i_ram genblk1_1_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[2].i_mem_a/i_ram genblk1_2_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[2].i_mem_b/i_ram genblk1_2_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[3].i_mem_a/i_ram genblk1_3_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[3].i_mem_b/i_ram genblk1_3_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[4].i_mem_a/i_ram genblk1_4_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[4].i_mem_b/i_ram genblk1_4_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[5].i_mem_a/i_ram genblk1_5_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[5].i_mem_b/i_ram genblk1_5_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[6].i_mem_a/i_ram genblk1_6_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[6].i_mem_b/i_ram genblk1_6_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[7].i_mem_a/i_ram genblk1_7_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[7].i_mem_b/i_ram genblk1_7_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[8].i_mem_a/i_ram genblk1_8_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[8].i_mem_b/i_ram genblk1_8_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[9].i_mem_a/i_ram genblk1_9_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[9].i_mem_b/i_ram genblk1_9_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[10].i_mem_a/i_ram genblk1_10_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[10].i_mem_b/i_ram genblk1_10_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[11].i_mem_a/i_ram genblk1_11_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[11].i_mem_b/i_ram genblk1_11_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[12].i_mem_a/i_ram genblk1_12_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[12].i_mem_b/i_ram genblk1_12_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[13].i_mem_a/i_ram genblk1_13_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[13].i_mem_b/i_ram genblk1_13_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[14].i_mem_a/i_ram genblk1_14_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[14].i_mem_b/i_ram genblk1_14_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk1[15].i_mem_a/i_ram genblk1_15_i_mem_a/i_ram -type BBOX BBOX
add mapped point genblk1[15].i_mem_b/i_ram genblk1_15_i_mem_b/i_ram -type BBOX BBOX
add mapped point genblk3[0].i_mul_wrapper_a/i_mul_a genblk3_0_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[0].i_mul_wrapper_b/i_mul_a genblk3_0_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[0].i_mul_wrapper_c/i_mul_a genblk3_0_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[1].i_mul_wrapper_a/i_mul_a genblk3_1_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[1].i_mul_wrapper_b/i_mul_a genblk3_1_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[1].i_mul_wrapper_c/i_mul_a genblk3_1_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[2].i_mul_wrapper_a/i_mul_a genblk3_2_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[2].i_mul_wrapper_b/i_mul_a genblk3_2_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[2].i_mul_wrapper_c/i_mul_a genblk3_2_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[3].i_mul_wrapper_a/i_mul_a genblk3_3_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[3].i_mul_wrapper_b/i_mul_a genblk3_3_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[3].i_mul_wrapper_c/i_mul_a genblk3_3_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[4].i_mul_wrapper_a/i_mul_a genblk3_4_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[4].i_mul_wrapper_b/i_mul_a genblk3_4_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[4].i_mul_wrapper_c/i_mul_a genblk3_4_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[5].i_mul_wrapper_a/i_mul_a genblk3_5_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[5].i_mul_wrapper_b/i_mul_a genblk3_5_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[5].i_mul_wrapper_c/i_mul_a genblk3_5_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[6].i_mul_wrapper_a/i_mul_a genblk3_6_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[6].i_mul_wrapper_b/i_mul_a genblk3_6_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[6].i_mul_wrapper_c/i_mul_a genblk3_6_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[7].i_mul_wrapper_a/i_mul_a genblk3_7_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[7].i_mul_wrapper_b/i_mul_a genblk3_7_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[7].i_mul_wrapper_c/i_mul_a genblk3_7_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[8].i_mul_wrapper_a/i_mul_a genblk3_8_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[8].i_mul_wrapper_b/i_mul_a genblk3_8_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[8].i_mul_wrapper_c/i_mul_a genblk3_8_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[9].i_mul_wrapper_a/i_mul_a genblk3_9_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[9].i_mul_wrapper_b/i_mul_a genblk3_9_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[9].i_mul_wrapper_c/i_mul_a genblk3_9_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[10].i_mul_wrapper_a/i_mul_a genblk3_10_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[10].i_mul_wrapper_b/i_mul_a genblk3_10_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[10].i_mul_wrapper_c/i_mul_a genblk3_10_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[11].i_mul_wrapper_a/i_mul_a genblk3_11_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[11].i_mul_wrapper_b/i_mul_a genblk3_11_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[11].i_mul_wrapper_c/i_mul_a genblk3_11_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[12].i_mul_wrapper_a/i_mul_a genblk3_12_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[12].i_mul_wrapper_b/i_mul_a genblk3_12_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[12].i_mul_wrapper_c/i_mul_a genblk3_12_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[13].i_mul_wrapper_a/i_mul_a genblk3_13_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[13].i_mul_wrapper_b/i_mul_a genblk3_13_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[13].i_mul_wrapper_c/i_mul_a genblk3_13_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[14].i_mul_wrapper_a/i_mul_a genblk3_14_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[14].i_mul_wrapper_b/i_mul_a genblk3_14_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[14].i_mul_wrapper_c/i_mul_a genblk3_14_i_mul_wrapper_c/i_mul_a -type BBOX BBOX
add mapped point genblk3[15].i_mul_wrapper_a/i_mul_a genblk3_15_i_mul_wrapper_a/i_mul_a -type BBOX BBOX
add mapped point genblk3[15].i_mul_wrapper_b/i_mul_a genblk3_15_i_mul_wrapper_b/i_mul_a -type BBOX BBOX
add mapped point genblk3[15].i_mul_wrapper_c/i_mul_a genblk3_15_i_mul_wrapper_c/i_mul_a -type BBOX BBOX



//Empty Modules as Blackboxes
