
//input ports
add mapped point clk_i clk_i -type PI PI
add mapped point rst_ni rst_ni -type PI PI
add mapped point operand_a_i[31] operand_a_i[31] -type PI PI
add mapped point operand_a_i[30] operand_a_i[30] -type PI PI
add mapped point operand_a_i[29] operand_a_i[29] -type PI PI
add mapped point operand_a_i[28] operand_a_i[28] -type PI PI
add mapped point operand_a_i[27] operand_a_i[27] -type PI PI
add mapped point operand_a_i[26] operand_a_i[26] -type PI PI
add mapped point operand_a_i[25] operand_a_i[25] -type PI PI
add mapped point operand_a_i[24] operand_a_i[24] -type PI PI
add mapped point operand_a_i[23] operand_a_i[23] -type PI PI
add mapped point operand_a_i[22] operand_a_i[22] -type PI PI
add mapped point operand_a_i[21] operand_a_i[21] -type PI PI
add mapped point operand_a_i[20] operand_a_i[20] -type PI PI
add mapped point operand_a_i[19] operand_a_i[19] -type PI PI
add mapped point operand_a_i[18] operand_a_i[18] -type PI PI
add mapped point operand_a_i[17] operand_a_i[17] -type PI PI
add mapped point operand_a_i[16] operand_a_i[16] -type PI PI
add mapped point operand_a_i[15] operand_a_i[15] -type PI PI
add mapped point operand_a_i[14] operand_a_i[14] -type PI PI
add mapped point operand_a_i[13] operand_a_i[13] -type PI PI
add mapped point operand_a_i[12] operand_a_i[12] -type PI PI
add mapped point operand_a_i[11] operand_a_i[11] -type PI PI
add mapped point operand_a_i[10] operand_a_i[10] -type PI PI
add mapped point operand_a_i[9] operand_a_i[9] -type PI PI
add mapped point operand_a_i[8] operand_a_i[8] -type PI PI
add mapped point operand_a_i[7] operand_a_i[7] -type PI PI
add mapped point operand_a_i[6] operand_a_i[6] -type PI PI
add mapped point operand_a_i[5] operand_a_i[5] -type PI PI
add mapped point operand_a_i[4] operand_a_i[4] -type PI PI
add mapped point operand_a_i[3] operand_a_i[3] -type PI PI
add mapped point operand_a_i[2] operand_a_i[2] -type PI PI
add mapped point operand_a_i[1] operand_a_i[1] -type PI PI
add mapped point operand_a_i[0] operand_a_i[0] -type PI PI
add mapped point operand_b_i[31] operand_b_i[31] -type PI PI
add mapped point operand_b_i[30] operand_b_i[30] -type PI PI
add mapped point operand_b_i[29] operand_b_i[29] -type PI PI
add mapped point operand_b_i[28] operand_b_i[28] -type PI PI
add mapped point operand_b_i[27] operand_b_i[27] -type PI PI
add mapped point operand_b_i[26] operand_b_i[26] -type PI PI
add mapped point operand_b_i[25] operand_b_i[25] -type PI PI
add mapped point operand_b_i[24] operand_b_i[24] -type PI PI
add mapped point operand_b_i[23] operand_b_i[23] -type PI PI
add mapped point operand_b_i[22] operand_b_i[22] -type PI PI
add mapped point operand_b_i[21] operand_b_i[21] -type PI PI
add mapped point operand_b_i[20] operand_b_i[20] -type PI PI
add mapped point operand_b_i[19] operand_b_i[19] -type PI PI
add mapped point operand_b_i[18] operand_b_i[18] -type PI PI
add mapped point operand_b_i[17] operand_b_i[17] -type PI PI
add mapped point operand_b_i[16] operand_b_i[16] -type PI PI
add mapped point operand_b_i[15] operand_b_i[15] -type PI PI
add mapped point operand_b_i[14] operand_b_i[14] -type PI PI
add mapped point operand_b_i[13] operand_b_i[13] -type PI PI
add mapped point operand_b_i[12] operand_b_i[12] -type PI PI
add mapped point operand_b_i[11] operand_b_i[11] -type PI PI
add mapped point operand_b_i[10] operand_b_i[10] -type PI PI
add mapped point operand_b_i[9] operand_b_i[9] -type PI PI
add mapped point operand_b_i[8] operand_b_i[8] -type PI PI
add mapped point operand_b_i[7] operand_b_i[7] -type PI PI
add mapped point operand_b_i[6] operand_b_i[6] -type PI PI
add mapped point operand_b_i[5] operand_b_i[5] -type PI PI
add mapped point operand_b_i[4] operand_b_i[4] -type PI PI
add mapped point operand_b_i[3] operand_b_i[3] -type PI PI
add mapped point operand_b_i[2] operand_b_i[2] -type PI PI
add mapped point operand_b_i[1] operand_b_i[1] -type PI PI
add mapped point operand_b_i[0] operand_b_i[0] -type PI PI

//output ports
add mapped point result_o[63] result_o[63] -type PO PO
add mapped point result_o[62] result_o[62] -type PO PO
add mapped point result_o[61] result_o[61] -type PO PO
add mapped point result_o[60] result_o[60] -type PO PO
add mapped point result_o[59] result_o[59] -type PO PO
add mapped point result_o[58] result_o[58] -type PO PO
add mapped point result_o[57] result_o[57] -type PO PO
add mapped point result_o[56] result_o[56] -type PO PO
add mapped point result_o[55] result_o[55] -type PO PO
add mapped point result_o[54] result_o[54] -type PO PO
add mapped point result_o[53] result_o[53] -type PO PO
add mapped point result_o[52] result_o[52] -type PO PO
add mapped point result_o[51] result_o[51] -type PO PO
add mapped point result_o[50] result_o[50] -type PO PO
add mapped point result_o[49] result_o[49] -type PO PO
add mapped point result_o[48] result_o[48] -type PO PO
add mapped point result_o[47] result_o[47] -type PO PO
add mapped point result_o[46] result_o[46] -type PO PO
add mapped point result_o[45] result_o[45] -type PO PO
add mapped point result_o[44] result_o[44] -type PO PO
add mapped point result_o[43] result_o[43] -type PO PO
add mapped point result_o[42] result_o[42] -type PO PO
add mapped point result_o[41] result_o[41] -type PO PO
add mapped point result_o[40] result_o[40] -type PO PO
add mapped point result_o[39] result_o[39] -type PO PO
add mapped point result_o[38] result_o[38] -type PO PO
add mapped point result_o[37] result_o[37] -type PO PO
add mapped point result_o[36] result_o[36] -type PO PO
add mapped point result_o[35] result_o[35] -type PO PO
add mapped point result_o[34] result_o[34] -type PO PO
add mapped point result_o[33] result_o[33] -type PO PO
add mapped point result_o[32] result_o[32] -type PO PO
add mapped point result_o[31] result_o[31] -type PO PO
add mapped point result_o[30] result_o[30] -type PO PO
add mapped point result_o[29] result_o[29] -type PO PO
add mapped point result_o[28] result_o[28] -type PO PO
add mapped point result_o[27] result_o[27] -type PO PO
add mapped point result_o[26] result_o[26] -type PO PO
add mapped point result_o[25] result_o[25] -type PO PO
add mapped point result_o[24] result_o[24] -type PO PO
add mapped point result_o[23] result_o[23] -type PO PO
add mapped point result_o[22] result_o[22] -type PO PO
add mapped point result_o[21] result_o[21] -type PO PO
add mapped point result_o[20] result_o[20] -type PO PO
add mapped point result_o[19] result_o[19] -type PO PO
add mapped point result_o[18] result_o[18] -type PO PO
add mapped point result_o[17] result_o[17] -type PO PO
add mapped point result_o[16] result_o[16] -type PO PO
add mapped point result_o[15] result_o[15] -type PO PO
add mapped point result_o[14] result_o[14] -type PO PO
add mapped point result_o[13] result_o[13] -type PO PO
add mapped point result_o[12] result_o[12] -type PO PO
add mapped point result_o[11] result_o[11] -type PO PO
add mapped point result_o[10] result_o[10] -type PO PO
add mapped point result_o[9] result_o[9] -type PO PO
add mapped point result_o[8] result_o[8] -type PO PO
add mapped point result_o[7] result_o[7] -type PO PO
add mapped point result_o[6] result_o[6] -type PO PO
add mapped point result_o[5] result_o[5] -type PO PO
add mapped point result_o[4] result_o[4] -type PO PO
add mapped point result_o[3] result_o[3] -type PO PO
add mapped point result_o[2] result_o[2] -type PO PO
add mapped point result_o[1] result_o[1] -type PO PO
add mapped point result_o[0] result_o[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point operand_a_i_sr[5]/q operand_a_i_sr_reg_5/Q -type DFF DFF
add mapped point operand_a_i_sr[3]/q operand_a_i_sr_reg_3/Q -type DFF DFF
add mapped point operand_a_i_sr[19]/q operand_a_i_sr_reg_19/Q -type DFF DFF
add mapped point operand_a_i_sr[15]/q operand_a_i_sr_reg_15/Q -type DFF DFF
add mapped point operand_b_i_sr[27]/q operand_b_i_sr_reg_27/Q -type DFF DFF
add mapped point operand_a_i_sr[14]/q operand_a_i_sr_reg_14/Q -type DFF DFF
add mapped point operand_a_i_sr[10]/q operand_a_i_sr_reg_10/Q -type DFF DFF
add mapped point operand_a_i_sr[8]/q operand_a_i_sr_reg_8/Q -type DFF DFF
add mapped point operand_b_i_sr[22]/q operand_b_i_sr_reg_22/Q -type DFF DFF
add mapped point operand_b_i_sr[13]/q operand_b_i_sr_reg_13/Q -type DFF DFF
add mapped point operand_b_i_sr[21]/q operand_b_i_sr_reg_21/Q -type DFF DFF
add mapped point operand_b_i_sr[20]/q operand_b_i_sr_reg_20/Q -type DFF DFF
add mapped point operand_a_i_sr[23]/q operand_a_i_sr_reg_23/Q -type DFF DFF
add mapped point operand_b_i_sr[18]/q operand_b_i_sr_reg_18/Q -type DFF DFF
add mapped point operand_a_i_sr[11]/q operand_a_i_sr_reg_11/Q -type DFF DFF
add mapped point operand_b_i_sr[16]/q operand_b_i_sr_reg_16/Q -type DFF DFF
add mapped point operand_b_i_sr[17]/q operand_b_i_sr_reg_17/Q -type DFF DFF
add mapped point operand_a_i_sr[31]/q operand_a_i_sr_reg_31/Q -type DFF DFF
add mapped point operand_a_i_sr[2]/q operand_a_i_sr_reg_2/Q -type DFF DFF
add mapped point operand_a_i_sr[0]/q operand_a_i_sr_reg_0/Q -type DFF DFF
add mapped point operand_b_i_sr[6]/q operand_b_i_sr_reg_6/Q -type DFF DFF
add mapped point operand_b_i_sr[5]/q operand_b_i_sr_reg_5/Q -type DFF DFF
add mapped point operand_b_i_sr[2]/q operand_b_i_sr_reg_2/Q -type DFF DFF
add mapped point operand_b_i_sr[1]/q operand_b_i_sr_reg_1/Q -type DFF DFF
add mapped point operand_b_i_sr[0]/q operand_b_i_sr_reg_0/Q -type DFF DFF
add mapped point operand_b_i_sr[30]/q operand_b_i_sr_reg_30/Q -type DFF DFF
add mapped point operand_b_i_sr[29]/q operand_b_i_sr_reg_29/Q -type DFF DFF
add mapped point operand_a_i_sr[26]/q operand_a_i_sr_reg_26/Q -type DFF DFF
add mapped point operand_b_i_sr[31]/q operand_b_i_sr_reg_31/Q -type DFF DFF
add mapped point operand_a_i_sr[27]/q operand_a_i_sr_reg_27/Q -type DFF DFF
add mapped point operand_b_i_sr[26]/q operand_b_i_sr_reg_26/Q -type DFF DFF
add mapped point operand_b_i_sr[24]/q operand_b_i_sr_reg_24/Q -type DFF DFF
add mapped point operand_b_i_sr[15]/q operand_b_i_sr_reg_15/Q -type DFF DFF
add mapped point operand_b_i_sr[14]/q operand_b_i_sr_reg_14/Q -type DFF DFF
add mapped point operand_b_i_sr[10]/q operand_b_i_sr_reg_10/Q -type DFF DFF
add mapped point operand_b_i_sr[8]/q operand_b_i_sr_reg_8/Q -type DFF DFF
add mapped point operand_a_i_sr[30]/q operand_a_i_sr_reg_30/Q -type DFF DFF
add mapped point operand_b_i_sr[28]/q operand_b_i_sr_reg_28/Q -type DFF DFF
add mapped point operand_a_i_sr[13]/q operand_a_i_sr_reg_13/Q -type DFF DFF
add mapped point operand_b_i_sr[25]/q operand_b_i_sr_reg_25/Q -type DFF DFF
add mapped point operand_a_i_sr[18]/q operand_a_i_sr_reg_18/Q -type DFF DFF
add mapped point operand_a_i_sr[16]/q operand_a_i_sr_reg_16/Q -type DFF DFF
add mapped point operand_a_i_sr[29]/q operand_a_i_sr_reg_29/Q -type DFF DFF
add mapped point operand_a_i_sr[21]/q operand_a_i_sr_reg_21/Q -type DFF DFF
add mapped point operand_b_i_sr[9]/q operand_b_i_sr_reg_9/Q -type DFF DFF
add mapped point operand_b_i_sr[23]/q operand_b_i_sr_reg_23/Q -type DFF DFF
add mapped point operand_b_i_sr[19]/q operand_b_i_sr_reg_19/Q -type DFF DFF
add mapped point operand_a_i_sr[7]/q operand_a_i_sr_reg_7/Q -type DFF DFF
add mapped point operand_a_i_sr[24]/q operand_a_i_sr_reg_24/Q -type DFF DFF
add mapped point operand_a_i_sr[1]/q operand_a_i_sr_reg_1/Q -type DFF DFF
add mapped point operand_b_i_sr[7]/q operand_b_i_sr_reg_7/Q -type DFF DFF
add mapped point operand_a_i_sr[17]/q operand_a_i_sr_reg_17/Q -type DFF DFF
add mapped point operand_b_i_sr[11]/q operand_b_i_sr_reg_11/Q -type DFF DFF
add mapped point operand_a_i_sr[12]/q operand_a_i_sr_reg_12/Q -type DFF DFF
add mapped point operand_a_i_sr[9]/q operand_a_i_sr_reg_9/Q -type DFF DFF
add mapped point operand_a_i_sr[25]/q operand_a_i_sr_reg_25/Q -type DFF DFF
add mapped point operand_a_i_sr[6]/q operand_a_i_sr_reg_6/Q -type DFF DFF
add mapped point operand_a_i_sr[4]/q operand_a_i_sr_reg_4/Q -type DFF DFF
add mapped point operand_b_i_sr[4]/q operand_b_i_sr_reg_4/Q -type DFF DFF
add mapped point operand_b_i_sr[12]/q operand_b_i_sr_reg_12/Q -type DFF DFF
add mapped point operand_a_i_sr[22]/q operand_a_i_sr_reg_22/Q -type DFF DFF
add mapped point operand_a_i_sr[20]/q operand_a_i_sr_reg_20/Q -type DFF DFF
add mapped point operand_a_i_sr[28]/q operand_a_i_sr_reg_28/Q -type DFF DFF
add mapped point operand_b_i_sr[3]/q operand_b_i_sr_reg_3/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
