tclmode

# Generated by Genus(TM) Synthesis Solution 23.15-s099_1, revision 1.578
# Generated on: Fri Nov 14 14:45:50 EET 2025 (Fri Nov 14 12:45:50 UTC 2025)

set_screen_display -noprogress
set_dofile_abort exit

### RTL names flow is enabled. ###
# Root attribute 'wlec_rtl_names_flow'        was 'true'.

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

set lec_version_required "19.10100"
if {$lec_version < $lec_version_required} {
    puts "// Error: Support for RTL names flow was added in LEC version 19.10-p100."
    puts "          A more recent version must be used."
    error ""
}

# Turns on the flowgraph datapath solver.
set wlec_analyze_dp_flowgraph true
# Indicates that resource sharing datapath optimization is present.
set share_dp_analysis         false

# The flowgraph solver is recommended for datapath analysis in LEC 19.1 or newer.
if {$wlec_analyze_dp_flowgraph} {
    set DATAPATH_SOLVER_OPTION "-flowgraph"
} elseif {$share_dp_analysis} {
    set DATAPATH_SOLVER_OPTION "-share"
} else {
    set DATAPATH_SOLVER_OPTION ""
}

tcl_set_command_name_echo on

set logfile logs/lec.syn_opt.log ;# user can modify this name for succeeding runs

set_log_file $logfile -replace

usage -auto -elapse

set_mapping_method -sensitive

set_verification_information fv_map_matmul_syncvgz_db

read_implementation_information fv/matmul_sync -golden fv_map -revised matmul_syncvgz -use_rtl_names

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 1,4 -norelease_license
set_compare_options -threads 1,4

set env(RC_VERSION)     "23.15-s099_1"
set env(CDN_SYNTH_ROOT) "/opt/soc/eda/cadence/DDI231/GENUS231/tools.lnx86"
set CDN_SYNTH_ROOT      "/opt/soc/eda/cadence/DDI231/GENUS231/tools.lnx86"
set env(CW_DIR) "/opt/soc/eda/cadence/DDI231/GENUS231/tools.lnx86/lib/chipware"
set CW_DIR      "/opt/soc/eda/cadence/DDI231/GENUS231/tools.lnx86/lib/chipware"
set lec_version_required "21.20249"
if { ($lec_version < $lec_version_required) &&
    [file exists /opt/soc/eda/cadence/DDI231/GENUS231/tools.lnx86/lib/chipware/old_encrypt_sim]} {
    set env(CW_DIR_SIM) "/opt/soc/eda/cadence/DDI231/GENUS231/tools.lnx86/lib/chipware/old_encrypt_sim"
    set CW_DIR_SIM      "/opt/soc/eda/cadence/DDI231/GENUS231/tools.lnx86/lib/chipware/old_encrypt_sim"
} else {
    set env(CW_DIR_SIM) "/opt/soc/eda/cadence/DDI231/GENUS231/tools.lnx86/lib/chipware/sim"
    set CW_DIR_SIM      "/opt/soc/eda/cadence/DDI231/GENUS231/tools.lnx86/lib/chipware/sim"
}
set_multiplier_implementation boothrca -both

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

set_hdl_option -UNSIZED_CONSTANT_TRUNCATE off

# ILM modules: 

add_search_path . /opt/soc/eda/cadence/DDI231/GENUS231/tools.lnx86/lib/tech -library -both
read_library -liberty -both \
    /opt/soc/tech/GPDK045/gsclib045/timing/slow_vdd1v0_basicCells.lib

read_design -verilog95   -golden -lastmod -noelab fv/matmul_sync/fv_map.v.gz
elaborate_design -golden -root {matmul_sync}

read_design -verilog95   -revised -lastmod -noelab /home/student/16/ex8/flow_matmul_sync_1/dbs/syn_opt.cdb/cmn/matmul_sync.v.gz
elaborate_design -revised -root {matmul_sync}

write_design -golden fv_map_matmul_syncvgz_db/elab.v -replace
report_design_data
report_black_box
report_modules

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -hier_seq_merge

puts "Dofile includes automatically generated DFT constraints. Carefully review the constraints"
puts "to ensure that functional logic is not excluded from verification."
puts "Use 'write_do_lec -no_dft' to comment out DFT constraints."
# Table of test_signals and related attributes
#
# Index  Pin                            Type             Dedicated  Has_fanout  Port/Pin    special test function      Dft_auto_created      User_defined  LEC_value                      
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
#  1      scan_mode_matmul_sync          test_mode        true       false       port        none                       true                  true          0          
#  2      scan_enable_matmul_sync        shift_enable     true       false       port        none                       true                  true          0          
#  3      rst_ni                         test_mode        true       true        port        none                       false                 true          auto       
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
# Warning : Multiple pin constraints are added to the revised design.
#          The constraints needed to disable test mode are not trivial.
#          It is possible that some valid functional modes will be excluded
#          from the formal verification process.
#          Review the constraints to ensure they are all expected
#          and appropriate.
add_pin_constraints 0 {scan_mode_matmul_sync} -golden
add_pin_constraints 0 {scan_enable_matmul_sync} -golden
add_pin_constraints 0 {scan_mode_matmul_sync} -revised
add_pin_constraints 0 {scan_enable_matmul_sync} -revised
add_ignored_outputs {scan_out_matmul_sync_0} -revised

analyze_extended_mapping fv/matmul_sync/fv_map.map.do fv/matmul_sync/matmul_syncvgz.map.do -output fv_map_matmul_syncvgz_1.map.do -input_specification rtl-n1 rtl-n2 -output_specification n1-n2 -replace -verbose
set lec_version_required "21.10142"
if {$lec_version >= $lec_version_required} {
    puts "For safety of verification, PIs and POs should be mapped by name."
    set_mapping_method -mapping_file_nopipo
}
set_mapping_method -search_in_mapping_file
set_analyze_option -mapping_file fv_map_matmul_syncvgz_1.map.do
check_mapping_setup -mapping_file_quality -summary

# Reports the quality of the implementation information.
# This command is only available with LEC 20.10-p100 or later.
set lec_version_required "20.10100"
if {$lec_version >= $lec_version_required} {
    check_verification_information
}

set_analyze_option -auto -report_map

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_compared_points noneq.compared_points.matmul_sync.fv_map.matmul_syncvgz.tcl -class noneq -tclmode -replace
set lec_version_required "21.10100"
if {$lec_version >= $lec_version_required} {
    analyze_nonequivalent -source_diagnosis
    report_nonequivalent_analysis > noneq.source_diag.matmul_sync.fv_map.matmul_syncvgz.rpt
}
report_test_vector -noneq > noneq.test_vector.matmul_sync.fv_map.matmul_syncvgz.rpt
write_verification_information
report_verification_information

# Reports how effective the implementation information was.
report_implementation_information

puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}

# Generate a detailed summary of the run.
analyze_results -logfiles $logfile

vpxmode

exit -f

